# Generated by Django 3.0.5 on 2020-04-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=255)),
                ('L_name', models.CharField(max_length=255)),
                ('Signup_U_name', models.CharField(max_length=255)),
                ('pwd1', models.CharField(max_length=10)),
                ('signup_email', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=13)),
                ('DOB', models.DateField()),
                ('Status', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
