# Generated by Django 3.0.5 on 2020-04-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign_up',
            name='contact',
            field=models.CharField(max_length=13),
        ),
    ]
