# Generated by Django 3.0.5 on 2020-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200428_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cont_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('email_addr', models.CharField(max_length=100)),
                ('ph_no', models.CharField(max_length=13)),
                ('Content', models.TextField()),
                ('timeStamp1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
